name: DevSecOps CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    # ---------------- SonarQube Scan ----------------

#    - name: SonarQube Scan
#      uses: SonarSource/sonarqube-scan-action@master
#      env:
 #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #      SONAR_HOST_URL: http://192.168.56.127:9000

    # ---------------- Gitleaks Scan ----------------

    - name: Gitleaks Scan
      uses: gitleaks/gitleaks-action@v2

    # ---------------- Docker Build ----------------

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest .

    # ---------------- Trivy Scan ----------------

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest
        severity: CRITICAL,HIGH

    # ---------------- Push Image ----------------

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest
